version: "3.8"

services:
    monero:
        image: exilesprx/xmrig:latest
        privileged: true
        env_file:
            - .env
    
    dero:
        image: exilesprx/dero:latest
        privileged: true
        env_file:
            - .env