services:
  source:
    build:
      context: .
      dockerfile: Dockerfile
      target: source
      tags:
        - exilesprx/xmrig:source

  build:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
      cache_from:
        - exilesprx/xmrig:source
      tags:
        - exilesprx/xmrig:build

  miner:
    build:
      context: .
      dockerfile: Dockerfile
      target: miner
      cache_from:
        - exilesprx/xmrig:build
      tags:
        - exilesprx/xmrig:miner