version: "3.8"

services:
    monero-miner:
        image: exilesprx/xmrig:latest
        privileged: true
        env_file:
            - .env
    
    dero-miner:
        image: exilesprx/dero:latest
        privileged: true
        env_file:
            - .env