version: "3.8"

services:
    monero:
        image: exilesprx/xmrig:10
        privileged: true
        env_file:
            - .env.monero
    
    dero:
        image: exilesprx/dero:latest
        privileged: true
        env_file:
            - .env.dero