services:

  source:
    image: exilesprx/xmrig:source
    build:
      context: .
      dockerfile: Dockerfile
      target: source

  build:
    image: exilesprx/xmrig:build
    build:
      context: .
      dockerfile: Dockerfile
      target: build
      cache_from:
        - exilesprx/xmrig:source