services:
  source:
    image: exilesprx/xmrig:source
    build:
      context: .
      dockerfile: Dockerfile
      target: source

  build:
    image: exilesprx/xmrig:build
    build:
      context: .
      dockerfile: Dockerfile
      target: build
      cache_from:
        - exilesprx/xmrig:source

  miner:
    image: exilesprx/xmrig:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: miner
      cache_from:
        - exilesprx/xmrig:build