version: "3.8"

services:
    monero:
        image: exilesprx/xmrig:release-v${RELEASE}
        privileged: true
        volumes:
            - ./xmrig.json:/etc/xmrig/xmrig.json
        environment:
            - CONFIG_FILE=/etc/xmrig/xmrig.json
        logging:
            driver: gelf
            options:
                gelf-address: "udp://localhost:12201"
                tag: "monero"
        depends_on:
            - graylog

    # MongoDB: https://hub.docker.com/_/mongo/
    mongo:
        image: mongo:6.0.9
        volumes:
            - mongo-data:/data/db

    elasticsearch:
        image: elasticsearch:7.17.12
        volumes:
            - es-data:/usr/share/elasticsearch/data
        environment:
            - http.host=0.0.0.0
            - transport.host=localhost
            - network.host=0.0.0.0
            - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        deploy:
            resources:
                limits:
                    memory: 1g

    # Graylog: https://hub.docker.com/r/graylog/graylog/
    graylog:
        image: graylog/graylog:5.1.4
        volumes:
            - graylog-data:/usr/share/graylog/data
        env_file:
            - .env.graylog
        entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
        restart: always
        depends_on:
            - mongo
            - elasticsearch
        ports:
            # Graylog web interface and REST API
            - 9000:9000
            # Syslog TCP
            - 1514:1514
            # Syslog UDP
            - 1514:1514/udp
            # GELF TCP
            - 12201:12201
            # GELF UDP
            - 12201:12201/udp

volumes:
    mongo-data:
        driver: local
    es-data:
        driver: local
    graylog-data:
        driver: local
