name: Docker Builds

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get source code and dependencies
        run: |
          docker compose -f docker-compose.build.yml build --pull source
          docker compose -f docker-compose.build.yml push source

      - name: Build XMrig
        run: |
          docker compose -f docker-compose.build.yml build --pull build
          docker compose -f docker-compose.build.yml push build

      - name: Verify Build
        run: docker run exilesprx/xmrig:build ldd ./xmrig

      - name: Create the miner
        run: |
          docker compose -f docker-compose.build.yml build --pull miner
          docker compose -f docker-compose.build.yml push miner