name: Docker Image

on:
  push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build source
        uses: docker/build-push-action@v4
        with:
          context: .
          pull: true
          push: true
          tags: exilesprx/xmrig:source
          target: source