name: Lint

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  lint:
    runs_on: ubuntu-latest
    steps:
      - actions/checkout@v3

      - name: Lint
        run: docker run --rm -i hadolint/hadolint < Dockerfile