name: Docker Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build release
        env:
          VERSION: ${{  github.ref_name }}
        run: |
          echo "Release $VERSION"
          docker compose -f docker-compose.build.yml build --pull miner
          docker compose -f docker-compose.build.yml push miner